GET http://localhost:8443/v1/wallet/POLYGON_MAINNET?address=0x01b72b4aa3f66f213d62d53e829bc172a6a72867
Content-Type: application/json

###
GET http://localhost:8443/v1/account/auth
Authorization: Bearer eyJraWQiOiIxOWJkMDRmOC1jNGRkLTQwZGYtYTc4NC1iY2Y5NTU5NmU2OTYiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE3MjQ3MjgyNTcsImFkZHJlc3MiOiIweDAxYjcyYjRhYTNmNjZmMjEzZDYyZDUzZTgyOWJjMTcyYTZhNzI4NjciLCJleHAiOjE3MjQ4MTQ2NTcsImlhdCI6MTcyNDcyODI1N30.Ng66FzUcsvAhAgUVc13un8i68CA3Uv4NXVJUgO8ZtdbjKE5RaHZENcS6V-vc0_dp9891I08a-OwJYICSwFYWxasVW1CXjYTFpj-8rt7x_a5D026L2YTqnBqwnXFcnpCNwZoDzoCkRrZuMI4Gqn_L3Zne8I4cP7qSi_Y-bw6-7Rb21oRdMgOY-P68wZIXWwWS9tEAJq3vecFUY1F1zs7dHnl1yixXJA5-7NONfGk40ap1mGNfcM7UtHVoZxLjeRMlhs_NN3LFOs89aqqnZLIrXNBCDsv9sqYQAoETSs4XQ28oNF0zzXyEAESaM5yBudWHieBV3htgC9vW670cRZCpbQ
Content-Type: application/json