GET http://localhost:8443/v1/wallet/POLYGON_MAINNET?address=0x01b72b4aa3f66f213d62d53e829bc172a6a72867
Content-Type: application/json

### accountNft 조회
GET http://localhost:8443/v1/account/auth/nft
Authorization: Bearer eyJraWQiOiIxOWJkMDRmOC1jNGRkLTQwZGYtYTc4NC1iY2Y5NTU5NmU2OTYiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE3MjcyNDQ5MTUsImFkZHJlc3MiOiIweDAxYjcyYjRhYTNmNjZmMjEzZDYyZDUzZTgyOWJjMTcyYTZhNzI4NjciLCJleHAiOjE3MjczMzEzMTUsImlhdCI6MTcyNzI0NDkxNX0.NZqqlru18_aYpvEvkTxL5kbjo-lMtKHeD8DFEcyH8tfUWom4TCMofwPtDMV5507gUY8zY3hABNW6UzDXG1qAw4QhIhEciO8dm9OvXJPxDYEQ5hzbwZXJ22k7Qugnsgu6MJ5l3AmoSDmefYv9DMF7V36nHsTLyxO4VDqlItCUPM-PQFMaXqv0CZOpvWsPcg_3GSNYj96zVhe1_gFa02EK7dAXEeB7wWYEzA83_Kkm7jd8Nxpcc2akjBV--Cg6r-ND46wbG62_vKrD_pSuSMvZLSwSec55VWLkEoGof6QTsGfqxQ9N0WCd5KfPnhqAiO8FzGPmem22yNxRvZ2zN_2CJA
Content-Type: application/json


### account조회
GET http://localhost:8443/v1/account/auth
Authorization: Bearer eyJraWQiOiIxOWJkMDRmOC1jNGRkLTQwZGYtYTc4NC1iY2Y5NTU5NmU2OTYiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE3MjcyNDQ5MTUsImFkZHJlc3MiOiIweDAxYjcyYjRhYTNmNjZmMjEzZDYyZDUzZTgyOWJjMTcyYTZhNzI4NjciLCJleHAiOjE3MjczMzEzMTUsImlhdCI6MTcyNzI0NDkxNX0.NZqqlru18_aYpvEvkTxL5kbjo-lMtKHeD8DFEcyH8tfUWom4TCMofwPtDMV5507gUY8zY3hABNW6UzDXG1qAw4QhIhEciO8dm9OvXJPxDYEQ5hzbwZXJ22k7Qugnsgu6MJ5l3AmoSDmefYv9DMF7V36nHsTLyxO4VDqlItCUPM-PQFMaXqv0CZOpvWsPcg_3GSNYj96zVhe1_gFa02EK7dAXEeB7wWYEzA83_Kkm7jd8Nxpcc2akjBV--Cg6r-ND46wbG62_vKrD_pSuSMvZLSwSec55VWLkEoGof6QTsGfqxQ9N0WCd5KfPnhqAiO8FzGPmem22yNxRvZ2zN_2CJA
Content-Type: application/json

### account log
GET http://localhost:8443/v1/account/auth/logs
Authorization: Bearer eyJraWQiOiIxOWJkMDRmOC1jNGRkLTQwZGYtYTc4NC1iY2Y5NTU5NmU2OTYiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE3MjcyNDQ5MTUsImFkZHJlc3MiOiIweDAxYjcyYjRhYTNmNjZmMjEzZDYyZDUzZTgyOWJjMTcyYTZhNzI4NjciLCJleHAiOjE3MjczMzEzMTUsImlhdCI6MTcyNzI0NDkxNX0.NZqqlru18_aYpvEvkTxL5kbjo-lMtKHeD8DFEcyH8tfUWom4TCMofwPtDMV5507gUY8zY3hABNW6UzDXG1qAw4QhIhEciO8dm9OvXJPxDYEQ5hzbwZXJ22k7Qugnsgu6MJ5l3AmoSDmefYv9DMF7V36nHsTLyxO4VDqlItCUPM-PQFMaXqv0CZOpvWsPcg_3GSNYj96zVhe1_gFa02EK7dAXEeB7wWYEzA83_Kkm7jd8Nxpcc2akjBV--Cg6r-ND46wbG62_vKrD_pSuSMvZLSwSec55VWLkEoGof6QTsGfqxQ9N0WCd5KfPnhqAiO8FzGPmem22yNxRvZ2zN_2CJA
Content-Type: application/json

### 회원가입
POST http://localhost:8443/v1/signin
Content-Type: application/json

{
  "address": "0x01b72b4aa3f66f213d62d53e829bc172a6a72867",
  "message": "Hello, MetaMask!",
  "signature": "0x5714c3d6a6773a614091a9ac81dc8f4f6a0219349ddb4010edb6595c47b158814a9265e2c17aa7f7cfe479636a96c9f93cd665b213cc76b005c4b742edb6b27c1c",
  "chain": "POLYGON_MAINNET"
}

### auth accress Token 재발급
POST http://localhost:8443/v1/api-auth/reissue
Content-Type: application/json
Authorization: Bearer eyJraWQiOiIxOWJkMDRmOC1jNGRkLTQwZGYtYTc4NC1iY2Y5NTU5NmU2OTYiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE3MjcyNDMwNjcsImFkZHJlc3MiOiIweDAxYjcyYjRhYTNmNjZmMjEzZDYyZDUzZTgyOWJjMTcyYTZhNzI4NjciLCJleHAiOjE3Mjc2NzUwNjcsImlhdCI6MTcyNzI0MzA2N30.fIRN39poqlfwUW4oDjW_cxYojbAuLqXWhIwH0-7lMQYorw34N6a7z2ePKwTKK7USuzumSFUP1rip58-v1nXInQ7Go2L1cIqjGUuObMndxNXT370cUgFt4nrCapeT8p7WKVa5XJ1bEsSThtfvuvP3U1Gzpi1xAKrA-jZ1E2JpP6vBs_XzxBFTNf1p5ERHAYfIKTn6DwxdsX1n1-fFO2oPTSZ8iasYqVfHWFVBxR4jsxRt3kmL8YARw7Mx8MPpfzzmGarbts5Shk3zp9KsJBRNVOEN1lRRJEevQEGXtMlAOYrz--x0_VY5kRL4OnlKWrV9Ov1onqu9E8UnmQN7R7OeKQ


### 지갑조회
GET http://localhost:8443/v1/wallet/POLYGON_AMOY?address=0x01b72b4aa3f66f213d62d53e829bc172a6a72867
Content-Type: application/json

### 지갑 NFT조회
GET http://localhost:8443/v1/wallet/nft?chainType=POLYGON_AMOY&address=0x01b72b4aa3f66f213d62d53e829bc172a6a72867&page=0&size=3
Content-Type: application/json

#### 입금
POST http://localhost:8443/v1/account/auth/deposit
Authorization: Bearer eyJraWQiOiIxOWJkMDRmOC1jNGRkLTQwZGYtYTc4NC1iY2Y5NTU5NmU2OTYiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE3MjcyNDQ5MTUsImFkZHJlc3MiOiIweDAxYjcyYjRhYTNmNjZmMjEzZDYyZDUzZTgyOWJjMTcyYTZhNzI4NjciLCJleHAiOjE3MjczMzEzMTUsImlhdCI6MTcyNzI0NDkxNX0.NZqqlru18_aYpvEvkTxL5kbjo-lMtKHeD8DFEcyH8tfUWom4TCMofwPtDMV5507gUY8zY3hABNW6UzDXG1qAw4QhIhEciO8dm9OvXJPxDYEQ5hzbwZXJ22k7Qugnsgu6MJ5l3AmoSDmefYv9DMF7V36nHsTLyxO4VDqlItCUPM-PQFMaXqv0CZOpvWsPcg_3GSNYj96zVhe1_gFa02EK7dAXEeB7wWYEzA83_Kkm7jd8Nxpcc2akjBV--Cg6r-ND46wbG62_vKrD_pSuSMvZLSwSec55VWLkEoGof6QTsGfqxQ9N0WCd5KfPnhqAiO8FzGPmem22yNxRvZ2zN_2CJA
Content-Type: application/json

{
  "chainType": "POLYGON_AMOY",
  "transactionHash": "0xb1c4782e93c4d44c343b10b1e980f880cc36983dbfa11c55a2f56b53f5a79ffb"
}


### ERC721 입금
POST http://localhost:8443/v1/account/auth/deposit
Authorization: Bearer eyJraWQiOiIxOWJkMDRmOC1jNGRkLTQwZGYtYTc4NC1iY2Y5NTU5NmU2OTYiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE3MjcyNDQ5MTUsImFkZHJlc3MiOiIweDAxYjcyYjRhYTNmNjZmMjEzZDYyZDUzZTgyOWJjMTcyYTZhNzI4NjciLCJleHAiOjE3MjczMzEzMTUsImlhdCI6MTcyNzI0NDkxNX0.NZqqlru18_aYpvEvkTxL5kbjo-lMtKHeD8DFEcyH8tfUWom4TCMofwPtDMV5507gUY8zY3hABNW6UzDXG1qAw4QhIhEciO8dm9OvXJPxDYEQ5hzbwZXJ22k7Qugnsgu6MJ5l3AmoSDmefYv9DMF7V36nHsTLyxO4VDqlItCUPM-PQFMaXqv0CZOpvWsPcg_3GSNYj96zVhe1_gFa02EK7dAXEeB7wWYEzA83_Kkm7jd8Nxpcc2akjBV--Cg6r-ND46wbG62_vKrD_pSuSMvZLSwSec55VWLkEoGof6QTsGfqxQ9N0WCd5KfPnhqAiO8FzGPmem22yNxRvZ2zN_2CJA
Content-Type: application/json

{
  "chainType": "POLYGON_AMOY",
  "transactionHash": "0x23718215bef33129a48da92667d79a261a870376cc523560dbfb43585415d7b8"
}

#### 출금 ERC20
POST http://localhost:8443/v1/account/auth/withdraw/ERC20
Authorization: Bearer eyJraWQiOiIxOWJkMDRmOC1jNGRkLTQwZGYtYTc4NC1iY2Y5NTU5NmU2OTYiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE3MjcyNDQ5MTUsImFkZHJlc3MiOiIweDAxYjcyYjRhYTNmNjZmMjEzZDYyZDUzZTgyOWJjMTcyYTZhNzI4NjciLCJleHAiOjE3MjczMzEzMTUsImlhdCI6MTcyNzI0NDkxNX0.NZqqlru18_aYpvEvkTxL5kbjo-lMtKHeD8DFEcyH8tfUWom4TCMofwPtDMV5507gUY8zY3hABNW6UzDXG1qAw4QhIhEciO8dm9OvXJPxDYEQ5hzbwZXJ22k7Qugnsgu6MJ5l3AmoSDmefYv9DMF7V36nHsTLyxO4VDqlItCUPM-PQFMaXqv0CZOpvWsPcg_3GSNYj96zVhe1_gFa02EK7dAXEeB7wWYEzA83_Kkm7jd8Nxpcc2akjBV--Cg6r-ND46wbG62_vKrD_pSuSMvZLSwSec55VWLkEoGof6QTsGfqxQ9N0WCd5KfPnhqAiO8FzGPmem22yNxRvZ2zN_2CJA
Content-Type: application/json

{
  "chainType": "POLYGON_AMOY",
  "amount": 1.2
}

#### 출금 ERC721
POST http://localhost:8443/v1/account/auth/withdraw/ERC721
Authorization: Bearer eyJraWQiOiIxOWJkMDRmOC1jNGRkLTQwZGYtYTc4NC1iY2Y5NTU5NmU2OTYiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE3MjcyNDQ5MTUsImFkZHJlc3MiOiIweDAxYjcyYjRhYTNmNjZmMjEzZDYyZDUzZTgyOWJjMTcyYTZhNzI4NjciLCJleHAiOjE3MjczMzEzMTUsImlhdCI6MTcyNzI0NDkxNX0.NZqqlru18_aYpvEvkTxL5kbjo-lMtKHeD8DFEcyH8tfUWom4TCMofwPtDMV5507gUY8zY3hABNW6UzDXG1qAw4QhIhEciO8dm9OvXJPxDYEQ5hzbwZXJ22k7Qugnsgu6MJ5l3AmoSDmefYv9DMF7V36nHsTLyxO4VDqlItCUPM-PQFMaXqv0CZOpvWsPcg_3GSNYj96zVhe1_gFa02EK7dAXEeB7wWYEzA83_Kkm7jd8Nxpcc2akjBV--Cg6r-ND46wbG62_vKrD_pSuSMvZLSwSec55VWLkEoGof6QTsGfqxQ9N0WCd5KfPnhqAiO8FzGPmem22yNxRvZ2zN_2CJA
Content-Type: application/json

{
  "nftId": 18
}